### ISSUE TITLE
Use correct field names from spreadsheet and upload remaining data

### ISSUE THREAD

**Issue by burieberry** [cardstack/boxel-archive-2021#133]

**Comment by KatrinN87** [comment]
Here's a list of text changes we need to do:

**Main page**

We need to say "masters" instead of "songs":
- for all catalogs (e.g. Golden Girl: "42 masters")
- in the sorting dropdown ("Masters A>Z", "Masters Z>A")
- in the third column of the table view

We need to add some sample data in table view:
- top artists => you can find them in the script (Part 1 p.30) or in the "Fake Catalog" doc (bottom of sheet 1)
- creation dates => same as above

**Catalog detail pages**

The catalog name should be consistently uppercased, if possible - e.g. right now, it’s "Master Recordings" < “Film music” at the top, but “Film Music” in the catalog name below.

Instead of “songs”, it should say “masters” in the top right corner (e.g. Film Music: “18 Masters”)

Instead of “song title”, it should just say “title” in table view (first column)

**Music detail pages**

Recording Details (view mode + edit mode): 
- “Artist” instead of “Writer”
- just "Language" instead of "Language Performance"
- Parental Advisory should be "No" for all recordings

Agreements (view mode + edit mode):
- the “assigner” and “assignee” should not have “(Ref)”, just the name ("Ref" was meant as a note, not as copy ;)).
- the ISRCs are not correct; the correct ones are in each “Master Recording Detail” doc
